GymnasiumApp/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('loginForm.urls')),
    path('', include('mainApp.urls')),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),  # browser searches at site.com/favicon for favicon, redirect to site.com/static/favicon
    ),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApp/urls.py
from django.urls import path
from . import views

app_name = 'mainApp'
urlpatterns = [
    path('', views.main_page, name='home'),
    path('noten', views.noten, name='noten'),
    path('absenzen', views.absenzen, name='absenzen'),
    path('panel', views.panel, name='panel'),
    path('klassen', views.klassen, name='klassen'),
    path('schuler/<int:student_id>/', views.detail, name='detail'),
    path('new-grade', views.new_grade, name='new-grade'),
    path('new-test', views.new_test, name='new-test'),
    path('new-thema', views.new_thema, name='new-thema'),
    path('schuler/<int:student_id>/noten/', views.all_grades, name='all_grades'),
    path('new-absenz', views.new_absenz, name='new-absenz'),
    path('schuler/<int:student_id>/absenzen/', views.all_absenzen, name='all_absenzen'),
    path('schuler/<int:student_id>/absenzen/<int:absenzen_id>/', views.absenzen_detail, name='absenzen_detail')
]

mainApp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Grade, Person, Test, Thema, Subject, Absenzen


# create a form
class NewGradeForm(ModelForm):
    def __init__(self, current_user, *args, **kwargs):
        super(NewGradeForm, self).__init__(*args, **kwargs)
        self.fields['student'].queryset = Person.objects.filter(klasse=current_user.klasse.id).exclude(pk=current_user.id).order_by('username')
        self.fields['test'].queryset = Test.objects.filter(thema__subject__teacher=current_user).order_by('date')

    class Meta:
        model = Grade
        fields = ['student', 'test', 'grade']
        labels = {
            'student': 'Schüler',
            'test': 'Prüfung',
            'grade': 'Note',
        }
        help_texts = {
            'grade': 'Die Note muss zwischen 1 und 6 sein'
        }


class NewTestForm(ModelForm):
    def __init__(self, current_user, *args, **kwargs):
        super(NewTestForm, self).__init__(*args, **kwargs)
        self.fields['thema'].queryset = Thema.objects.filter(subject__teacher=current_user).order_by('-created_at')

    class Meta:
        model = Test
        fields = ['thema', 'school_class', 'weight', 'date']
        labels = {
            'thema': 'Thema',
            'school_class': 'Klasse',
            'weight': 'Gewichtung',
            'date': 'Datum'
        }


class NewThemaForm(ModelForm):
    def __init__(self, current_user, *args, **kwargs):
        super(NewThemaForm, self).__init__(*args, **kwargs)
        self.fields['subject'].queryset = Subject.objects.filter(teacher=current_user)

    class Meta:
        model = Thema
        fields = '__all__'
        labels = {
            'subject': 'Fach',
            'thema': 'Thema'
        }


class NewAbsenzForm(ModelForm):
    def __init__(self, current_user, *args, **kwargs):
        super(NewAbsenzForm, self).__init__(*args, **kwargs)
        self.fields['student'].queryset = Person.objects.filter(klasse=current_user.klasse.id).exclude(pk=current_user.id).order_by('first_name')
        self.fields['subject'].queryset = Subject.objects.filter(teacher=current_user)

    class Meta:
        model = Absenzen
        fields = '__all__'
        labels = {
            'student': 'Schüler',
            'subject': 'Fach',
            'date': 'Datum',
            'notes': 'Notizen',
        }


class UploadImageAbsenzForm(ModelForm):
    class Meta:
        model = Absenzen
        fields = ['image']
        labels = {
            'image': 'Bild von Entschuldigung'
        }
        widgets = {
            'image': forms.FileInput(attrs={'type': 'file'})
        }

mainApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from .models import Subject, Absenzen, SchoolClass, Person, Grade
from .forms import NewTestForm, NewGradeForm, NewThemaForm, NewAbsenzForm, UploadImageAbsenzForm
from django.contrib import messages
import os

# Create your views here.
# POST Logout muss nur in der View für Index getestet werden, da in HTML action="." --> Post wird zu root weitergeleitet


def main_page(request):
    if request.user.is_authenticated:  # if user is logged in
        if request.method == "POST":
            if request.POST['logout'] == 'logout':  # check if post is for logout
                logout(request)  # logout the user
                return redirect('loginForm:login')
        else:
            recent_grades = Grade.get_recent_grades(student_id=request.user.id)
            subject_list_query = list(Subject.get_subjects())
            grades = Grade.get_grades(student=request.user.id, subjects=subject_list_query)
            grades_sum_dict = Grade.get_avg_subject(grades=grades)
            grades_avg = list(grades_sum_dict.values())
            subject_list = list(grades_sum_dict.keys())  # so only subject with grades are passed
            return render(request, 'index.html', {'recent_grades': recent_grades, 'subjects': subject_list, 'grades_avg': grades_avg})

    else:  # else redirect to login page
        return redirect('loginForm:login')


def noten(request):
    if request.user.is_authenticated:  # if user is logged in
        subject_list = Subject.get_subjects()
        grades = Grade.get_grades(student=request.user.id, subjects=subject_list)
        grades_sum_dict = Grade.get_avg_subject(grades=grades)
        return render(request, 'noten.html', {'grades_dict': grades, 'grades_sum_dict': grades_sum_dict})
    else:  # else redirect to login page
        return redirect('loginForm:login')


def absenzen(request):
    if request.user.is_authenticated:  # if user is logged in
        if request.method == 'POST':
            if 'detail' in request.POST:
                return redirect(f'/schuler/{request.user.id}/absenzen/{request.POST.get("detail")}')
        absenzen_local = Absenzen.get_absenzen(student=request.user.id)
        absenzen_sum_local = Absenzen.get_sum(absenzen_dict=absenzen_local)
        return render(request, 'absenzen.html', {'absenzen_dict': absenzen_local, 'absenzen_sum_dict': absenzen_sum_local})
    else:  # else redirect to login page
        return redirect('loginForm:login')


def panel(request):
    if request.user.is_authenticated:
        if request.user.is_teacher():
            if request.method == "POST":
                if request.POST.get('new-grade') == 'new-grade':
                    return redirect('mainApp:new-grade')
                elif request.POST.get('new-theme') == 'new-theme':
                    return redirect('mainApp:new-thema')
                elif request.POST.get('new-absenz') == 'new-absenz':
                    return redirect('mainApp:new-absenz')
            klasse = SchoolClass.get_class_of_teacher(request.user.id)
            return render(request, 'panel.html', {'klasse': klasse})
        else:
            return redirect('mainApp:home')
    else:  # else redirect to login page
        return redirect('loginForm:login')


def klassen(request):
    if request.user.is_authenticated:
        if request.user.is_teacher():
            class_list = SchoolClass.get_classes()
            student_dict = SchoolClass.get_students_classes(class_names=class_list)
            return render(request, 'klassen.html', {'student_dict': student_dict})
        else:
            return redirect('mainApp:home')
    else:  # else redirect to login page
        return redirect('loginForm:login')


def detail(request, student_id):
    if request.user.is_authenticated:
        if request.user.is_teacher():
            student = get_object_or_404(Person, pk=student_id)
            recent_grades = Grade.get_recent_grades(student_id=student_id)
            return render(request, 'schuler.html', {'student': student, 'recent_grades': recent_grades})
        else:
            return redirect('mainApp:home')
    else:  # else redirect to login page
        return redirect('loginForm:login')


def new_grade(request):
    if request.user.is_authenticated:
        if request.user.is_teacher():
            if request.method == 'POST':
                if request.POST.get('new-grade-form') == 'new-grade':
                    form = NewGradeForm(current_user=request.user, data=request.POST)
                    if form.is_valid():
                        form.save()
                        messages.success(request, "Die Note wurde erfolgreich eingetragen!")
                    else:
                        messages.error(request, "Der Vorgang ist fehlgeschlagen, bitte versuchen Sie es erneut!")
            form = NewGradeForm(current_user=request.user)
            return render(request, 'new-grade.html', {'form': form})
        else:
            return redirect('mainApp:home')
    else:
        return redirect('loginForm:login')


def new_test(request):
    if request.user.is_authenticated:
        if request.user.is_teacher():
            if request.method == 'POST':
                if request.POST.get('new-test-form') == 'new-test':
                    form = NewTestForm(data=request.POST, current_user=request.user)
                    if form.is_valid():
                        form.save()
                        messages.success(request, "Der Test wurde erfolgreich erstellt!")
                        return redirect('mainApp:new-grade')
                    else:
                        messages.error(request, "Der Vorgang ist fehlgeschlagen, bitte versuchen Sie es erneut!")
            form = NewTestForm(current_user=request.user)
            return render(request, 'new-test.html', {'form': form})
        else:
            return redirect('mainApp:home')
    else:
        return redirect('loginForm:login')


def new_thema(request):
    if request.user.is_authenticated:
        if request.user.is_teacher():
            if request.method == 'POST':
                if request.POST.get('new-thema-form') == 'new-thema':
                    form = NewThemaForm(current_user=request.user, data=request.POST)
                    if form.is_valid():
                        form.save()
                        messages.success(request, "Das Thema wurde erfolgreich erstellt!")
                        next_site = request.POST.get('next', '/')
                        return redirect(next_site)
                    else:
                        messages.error(request, "Der Vorgang ist fehlgeschlagen, bitte versuchen Sie es erneut!")
            form = NewThemaForm(current_user=request.user)
            return render(request, 'new_thema.html', {'form': form})
        else:
            return redirect('mainApp:home')
    else:
        return redirect('loginForm:login')


def all_grades(request, student_id):
    if request.user.is_authenticated:
        if request.user.is_teacher():
            if request.method == 'POST':
                if 'delete' in request.POST:
                    Grade.objects.filter(pk=request.POST.get('delete')).delete()
            subject_list = Subject.get_subjects()
            grades = Grade.get_grades(student=student_id, subjects=subject_list)
            grades_sum_dict = Grade.get_avg_subject(grades=grades)
            student = get_object_or_404(Person, pk=student_id)
            return render(request, 'all_grades.html', {'grades_dict': grades, 'grades_sum_dict': grades_sum_dict, 'student': student})
        else:
            return redirect('mainApp:home')
    return redirect('loginForm:login')


def new_absenz(request):
    if request.user.is_authenticated:
        if request.user.is_teacher():
            if request.method == 'POST':
                if request.POST.get('new-absenz-form') == 'new-absenz':
                    form = NewAbsenzForm(current_user=request.user, data=request.POST)
                    if form.is_valid():
                        form.save()
                        messages.success(request, "Die Absenz wurde erfolgreich erstellt!")
                        return redirect('mainApp:new-absenz')
                    else:
                        messages.error(request, "Der Vorgang ist fehlgeschlagen, bitte versuchen Sie es erneut!")
            form = NewAbsenzForm(current_user=request.user)
            return render(request, 'new_absenz.html', {'form': form})
        else:
            return redirect('mainApp:home')
    else:
        return redirect('loginForm:login')


def all_absenzen(request, student_id):
    if request.user.is_authenticated:
        if request.user.is_teacher():
            if request.method == 'POST':
                if 'detail' in request.POST:
                    return redirect(f'/schuler/{student_id}/absenzen/{request.POST.get("detail")}')
            absenzen_local = Absenzen.get_absenzen(student=student_id)
            absenzen_sum_local = Absenzen.get_sum(absenzen_dict=absenzen_local)
            student = get_object_or_404(Person, pk=student_id)
            return render(request, 'all_absenzen.html', {'absenzen_dict': absenzen_local, 'absenzen_sum_dict': absenzen_sum_local, 'student': student})
        else:
            return redirect('mainApp:home')
    else:
        return redirect('loginForm:login')


def absenzen_detail(request, student_id, absenzen_id):
    if request.user.is_authenticated:
        if request.user.id == student_id or request.user.is_teacher():
            absenz = Absenzen.objects.get(pk=absenzen_id)
            form = UploadImageAbsenzForm(instance=absenz)
            student = get_object_or_404(Person, pk=student_id)
            absenzen_local = Absenzen.get_absenzen(student=student_id, absenz_id=absenzen_id)
            if request.method == 'POST':
                if request.user.is_teacher():

mainApp/templates/absenzen.html
{% extends 'layout.html' %}
{% load main_extra %}

{% block body %}

    <main>
        <div class="personal-info">
            <h1>
                <u>Absenzen:</u>
            </h1>
            {% if absenzen_dict %}
                {% for subject, absenzen in absenzen_dict.items  %}
                    <button class="{{ absenzen_dict.keys|get_class_button:subject }}" type="button" onclick="collapse_show_button(this)">
                        <strong>{{ subject }}</strong> {% if absenzen_sum_dict|get_item:subject > 0 %}<div class="items-align-right round-border">({{ absenzen_sum_dict|get_item:subject }})</div>{% endif %}
                    </button>
                    <div class="content">
                        {% if absenzen %}
                            <ul>
                                {% for absenzen_dict in absenzen %}
                                    <div class="content-text">
                                        <form method="POST" action="{% url 'mainApp:absenzen' %}">{% csrf_token %}<button type="submit" name="detail" value="{{ absenzen_dict.ID }}" class="items-align-right small-button" style="top: 50%">Absenz anschauen</button></form>
                                        <li>Entschuldigt: {{ absenzen_dict.Entschuldigt }}</li>
                                        {% if absenzen_dict.Entschuldigt == 'Nein' %}
                                            {% if absenzen_dict.Abgelaufen %}
                                                <p><strong>Abgabedatum schon abgelaufen</strong></p>
                                            {% else %}
                                                <p>--> Abgabedatum: {{ absenzen_dict.Abgabedatum }}</p>
                                            {% endif %}
                                        {% else %}
                                            <p>Abgegeben</p>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <div class="content-text">
                                <p>Du hast noch keine Absenzen in diesem Fach.</p>
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
                {% else %}
                <p>Noch keine Fächer eingetragen!</p>
            {% endif %}
        </div>
    </main>
{% endblock %}

mainApp/templates/absenzen_detail.html
{% extends 'layout.html' %}
{% load main_extra %}
{% load crispy_forms_tags %}

{% block body %}
    <main>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <i class="bi bi-exclamation-triangle-fill"></i> {{ message }}
                        <button type="button" class="close" aria-label="Close" data-bs-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% elif message.tags == 'success' %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <i class="bi bi-check-circle-fill"></i> {{ message }}
                        <button type="button" class="close" aria-label="Close" data-bs-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% elif message.tags == 'warning' %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <i class="bi bi-check-circle-fill"></i> {{ message }}
                        <button type="button" class="close" aria-label="Close" data-bs-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        <div class="personal-info">
            <h1>
                <u>Absenz Nr. {{ absenz.ID }} für {{ student.first_name }} {{ student.last_name }}:</u>
            </h1>
            {% if user.is_teacher %}
                <br>
                {% if absenz.Entschuldigt == 'Nein' %}
                    <form method="POST"
                          action="{% url 'mainApp:absenzen_detail' student.id absenz.ID %}">{% csrf_token %}
                        <button type="submit" name="excuse" value="{{ absenz.ID }}" class="small-button"
                                style="top: 50%">Absenz als entschuldigt eintragen
                        </button>
                    </form>
                {% else %}
                    <form method="POST"
                          action="{% url 'mainApp:absenzen_detail' student.id absenz.ID %}">{% csrf_token %}
                        <button type="submit" name="not-excused" value="{{ absenz.ID }}" class="small-button"
                                style="top: 50%">Absenz als unentschuldigt eintragen
                        </button>
                    </form>
                {% endif %}
                <br>
            {% endif %}
            <ul style="margin-left: 20px;">
                <li>Entschuldigt: {{ absenz.Entschuldigt }}</li>
                <li>Abgabedatum: {{ absenz.Abgabedatum }}</li>
                <li>Fach: {{ absenz.Fach }}</li>
            </ul>
            {% if absenz.Notizen %}
                <h3>
                    <u>Notizen:</u>
                </h3>
                {{ absenz.Notizen }}
            {% endif %}
            <br>
            {% if not absenz.Bild and not user.is_teacher %}
                <form action="{% url 'mainApp:absenzen_detail' student.id absenz.ID %}" method="POST" class="form-group"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-outline mb-3" style="width:50%">
                        {{ form.image|as_crispy_field }}
                    </div>
                    <button type="submit" class="btn btn-primary btn-block mb-4" style="width:50%"
                            name="new-absenz-image" value="new-absenz-image">Bild hochladen
                    </button>
                </form>
            {% elif absenz.Bild and not user.is_teacher %}
                <h3>
                    <br>
                    Bild der Entschuldigung:
                </h3>
                <div class="show-image" onmouseover="delete_image_button()" onmouseout="normal_state()">
                    <img src="{{ absenz.Bild.url }}" generator-unable-to-provide-required-alt="" class="image">
                    <form action="{% url 'mainApp:absenzen_detail' student.id absenz.ID %}" method="POST"
                          class="form-group">
                        {% csrf_token %}
                        <button type="submit" class="delete-image small-button" name="delete-image" id="delete-image"
                                value="delete-image">Bild löschen
                        </button>
                    </form>
                </div>
            {% elif absenz.Bild %}
                <h3>
                    <br>
                    Bild der Entschuldigung:
                </h3>
                <img src="{{ absenz.Bild.url }}" generator-unable-to-provide-required-alt="" class="image">
            {% else %}
                <h3>
                    <br>
                    <i>Der Schüler hat noch kein Bild hochgeladen</i>
                </h3>
            {% endif %}
        </div>
    </main>
{% endblock %}

mainApp/templates/all_absenzen.html
{% extends 'layout.html' %}
{% load main_extra %}

{% block body %}

    <main>
        <div class="personal-info">
            <h1>
                <u>Absenzen von {{ student.first_name }} {{ student.last_name }}:</u>
            </h1>
            {% if absenzen_dict %}
                {% for subject, absenzen in absenzen_dict.items  %}
                    <button class="{{ absenzen_dict.keys|get_class_button:subject }}" type="button" onclick="collapse_show_button(this)">
                        <strong>{{ subject }}</strong> {% if absenzen_sum_dict|get_item:subject > 0 %}<div class="items-align-right round-border">({{ absenzen_sum_dict|get_item:subject }})</div>{% endif %}
                    </button>
                    <div class="content">
                        {% if absenzen %}
                            <ul>
                                {% for absenzen_dict in absenzen %}
                                    <div class="content-text">
                                        <form method="POST" action="{% url 'mainApp:all_absenzen' student.id %}">{% csrf_token %}<button type="submit" name="detail" value="{{ absenzen_dict.ID }}" class="items-align-right small-button" style="top: 50%">Absenz anschauen</button></form>
                                        <li>Entschuldigt: {{ absenzen_dict.Entschuldigt }}</li>
                                        {% if absenzen_dict.Entschuldigt == 'Nein' %}
                                            {% if absenzen_dict.Abgelaufen %}
                                                <p><strong>Abgabedatum schon abgelaufen</strong></p>
                                            {% else %}
                                                <p>--> Abgabedatum: {{ absenzen_dict.Abgabedatum }}</p>
                                            {% endif %}
                                        {% else %}
                                            <p>Abgegeben</p>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <div class="content-text">
                                <p>{{ student.first_name }} {{ student.last_name }} hat noch keine Absenzen in diesem Fach.</p>
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
                {% else %}
                <p>Noch keine Fächer eingetragen!</p>
            {% endif %}
        </div>
    </main>
{% endblock %}

mainApp/templates/all_grades.html
{% extends 'layout.html' %}
{% load main_extra %}

{% block body %}
    <main>
        <div class="personal-info">
            <h1>
                <u>Noten von {{ student.first_name }} {{ student.last_name }}:</u> {% if student.id|get_average_all != None %}({{ student.id|get_average_all }}){% endif %}
            </h1>
            {% if grades_dict %}
                {% for subject, grades in grades_dict.items %}
                    <button class="{{ grades_dict.keys|get_class_button:subject }}" type="button" onclick="collapse_show_button(this)">
                        <strong>{{ subject }}</strong> {% if grades_sum_dict|get_item:subject != None %}<div class="noten-avg items-align-right round-border">({{ grades_sum_dict|get_item:subject }})</div>{% endif %}
                    </button>
                    <div class="content">
                        {% if grades %}
                            <ul>
                                {% for grade in grades %}
                                    <div class="content-text">
                                        <li>Note: <strong>{{ grade.Note }}</strong>{% if grade.Thema != None %} ({{ grade.Thema }}) {% endif %}</li><form method="POST" action="{% url 'mainApp:all_grades' student.id %}">{% csrf_token %}<button type="submit" name="delete" value="{{ grade.ID }}" class="items-align-right small-button">Note löschen</button></form>
                                        Datum: {{ grade.Datum }}
                                        <br>
                                        Gewichtung: {{ grade.Gewichtung }}
                                        {% if user.klasse|get_avg_class:grade.Thema != None%}
                                        <br>
                                        Klassenschnitt: {{ user.klasse|get_avg_class:grade.Thema }}
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <div class="content-text">
                                <p>{{ student.first_name }} {{ student.last_name }} hat noch keine Noten in diesem Fach!</p>
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
                {% else %}
                <p>Noch keine Fächer eingetragen!</p>
            {% endif %}
        </div>
    </main>
{% endblock %}

mainApp/templates/schuler.html
{% extends 'layout.html' %}
{% load main_extra %}

{% block body %}
    <main>
        <div class="personal-info">
            <h1>
                <u>Schüler Informationen:</u>
            </h1>
            <p>
                {% if student.first_name|length > 0 and student.last_name|length > 0 %}
                    Name: {{ student.first_name }} {{ student.last_name }}
                {% else %}
                    Name: <strong>Kein Name angegeben, bitte wenden Sie sich an ihren Administrator!</strong>
                {% endif %}
                <br>
                {% if student.klasse %}
                    Klasse: {{ student.klasse }}
                    <br>
                {% endif %}
                {% if student.email|length > 0 %}
                    E-Mail: {{ student.email }}
                {% else %}
                    E-Mail: <strong>Keine E-Mail angegeben, bitte wenden Sie sich an ihren Administrator!</strong>
                {% endif %}
                <br>
                Adresse: {{ student.return_address }}
                <br>
                {% if student.get_age > 10 %}
                    Alter: {{ student.get_age }} Jahre
                {% else %}
                    Alter: <strong>Kein Alter angegeben, bitte wenden Sie sich an ihren Administrator!</strong>
                {% endif %}
            </p>
            <form action="{% url 'mainApp:all_absenzen' student.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="small-button">Alle Absenzen von {{ student.first_name }} {{ student.last_name }}</button>
            </form>
            <br>
            <div style="width:50%">
                {% if recent_grades %}
                <form action="{% url 'mainApp:all_grades' student.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="small-button-align-right small-button">Alle Noten von {{ student.first_name }} {{ student.last_name }}</button>
                </form>
                {% endif %}
                <h1>
                    <u>Neueste Noten:</u>
                </h1>
            </div>
            {% if recent_grades %}
                {% for grade in recent_grades %}
                    <button class="{{ recent_grades|get_class_button:grade }}" type="button" onclick="collapse_show_button(this)">
                        <strong>{{ grade.Note }}</strong> ({{ grade.Fach }})
                    </button>
                    <div class="content">
                        <div class="content-text">
                            <p>
                                {% if grade.Thema != None %}Thema: {{ grade.Thema }}<br>{% endif %}
                                Datum: {{ grade.Datum }}
                                <br>
                                Gewichtung: {{ grade.Gewichtung }}
                                {% if student.klasse|get_avg_class:grade.Thema %}
                                    <br>
                                    Klassenschnitt: {{ student.klasse|get_avg_class:grade.Thema }}
                                {% endif %}
                            </p>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>Dieser Schüler hat noch keine Noten</p>
            {% endif %}
        </div>
    </main>
{% endblock body %}